export const CLINIC = {
  name: 'Infinity Clinics',
  tagline: 'Omkar Nagar · Nagpur',
  phone: '8888797624',
  phoneDisplay: '8888 797 624',
  email: 'info@infinityclinics.com',
  address: 'House No. 8863-94, Chandrabhaga Layout, Manewada Ring Road, Omkar Nagar, Nagpur – 440027, Maharashtra',
  ribbon: 'House No. 8863-94, Chandrabhaga Layout, Manewada Ring Road, Omkar Nagar, Nagpur – 440027',
  mapQuery: 'Infinity+Clinics+Manewada+Ring+Road+Omkar+Nagar+Nagpur+440027',
  whatsapp: '918888797624',
  landmark: 'Beside The South Point Public School (Nursery – 10th, CBSE)',
  established: 'Multi-specialty practice · Omkar Nagar',
};

export const DEPARTMENTS = [
  {
    id: 'heart',
    num: '01',
    color: 'heart',
    slug: 'cardiology',
    dept: 'Infinity Heart Clinic',
    name: 'Dr. Mahendra Maske',
    shortName: 'Dr. Maske',
    cred: 'MBBS · MD Internal Medicine (Gold Medallist) · DM Cardiology',
    role: 'Consultant Interventional Cardiologist',
    experience: '18+ years in cardiology',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹800',
    bio: 'Dr. Maske leads the heart clinic with DM Cardiology and gold-medal internal medicine training. He manages everything from routine hypertension follow-ups to interventional procedures — angiography and angioplasty — so patients do not need to shuttle between a clinic and a separate cath lab for common cardiac work.',
    whenToVisit: ['Chest pain or tightness', 'High blood pressure or diabetes with heart risk', 'Palpitations or irregular heartbeat', 'Breathlessness on exertion', 'Post-heart-attack follow-up', 'Pre-surgery cardiac clearance'],
    services: ['Angiography', 'Angioplasty', 'ECG', '2D-ECHO', 'TMT'],
    serviceDetails: [
      { name: 'ECG & 2D-ECHO', desc: 'Same-visit cardiac imaging — no separate lab appointment for basic heart assessment.' },
      { name: 'TMT (Stress Test)', desc: 'Treadmill testing for exercise-induced symptoms and fitness clearance.' },
      { name: 'Angiography & Angioplasty', desc: 'Interventional procedures for blocked arteries, performed by a DM Cardiologist.' },
    ],
    note: 'For chest pain, hypertension, diabetes & heart-rhythm concerns',
    signpost: { label: 'Heart Clinic', doctor: 'Dr. Maske' },
  },
  {
    id: 'ent',
    num: '02',
    color: 'ent',
    slug: 'ent',
    dept: 'ENT Clinic',
    name: 'Dr. Prasann Moon',
    shortName: 'Dr. Moon',
    cred: 'MBBS · MS · DNB-ENT · MNAMS',
    role: 'Certified in Vertigo & Endoscopic Sinus Surgery',
    experience: 'ENT surgeon with advanced sinus & balance training',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹600',
    bio: 'Dr. Moon handles the full spectrum of ear, nose and throat conditions — from childhood ear infections to adult sinus disease and vertigo. Endoscopic sinus surgery and hearing-aid fitting are available on-site, so most ENT complaints are resolved without a hospital referral.',
    whenToVisit: ['Chronic sinusitis or nasal blockage', 'Recurrent ear infections', 'Hearing loss or ringing (tinnitus)', 'Dizziness or vertigo', 'Throat pain or voice changes', 'Thyroid swelling in the neck'],
    services: ['Allergy', 'Endoscopy', 'Vertigo / Dizziness', 'Thyroid', 'Hearing aid fitting'],
    serviceDetails: [
      { name: 'Endoscopic Sinus Surgery', desc: 'Minimally invasive treatment for chronic sinus and nasal polyps.' },
      { name: 'Vertigo & Balance Clinic', desc: 'Specialised assessment for dizziness, BPPV and inner-ear disorders.' },
      { name: 'Hearing Aid Fitting', desc: 'Evaluation and fitting for age-related or noise-induced hearing loss.' },
    ],
    note: 'Ear, nose, throat & balance disorders',
    signpost: { label: 'ENT Clinic', doctor: 'Dr. Moon' },
  },
  {
    id: 'ortho',
    num: '03',
    color: 'ortho',
    slug: 'orthopaedics',
    dept: 'हाडांचा दवाखाना — Bone & Joint',
    name: 'Dr. Gunjan Kolhe',
    shortName: 'Dr. Kolhe',
    cred: "MBBS · D'Ortho · FIJR · FIAS — Orthopaedic Surgeon",
    role: 'Fellowship: Arthroscopy & Joint Replacement (Pune, Mumbai)',
    experience: 'Fellowship-trained orthopaedic surgeon',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹700',
    bio: 'Dr. Kolhe specialises in joints, sports injuries and spine care. With fellowship training in arthroscopy and joint replacement from Pune and Mumbai, he offers surgical and non-surgical options for knee, shoulder and hip problems — from fracture fixation to keyhole arthroscopy.',
    whenToVisit: ['Knee or shoulder pain', 'Sports injuries', 'Fractures and trauma', 'Joint stiffness or arthritis', 'Back pain and spondylosis', 'Difficulty walking or climbing stairs'],
    services: ['Arthroscopy', 'Joint Replacement', 'Spine', 'Trauma', 'Pain Management'],
    serviceDetails: [
      { name: 'Arthroscopy', desc: 'Keyhole surgery for ACL tears, meniscus damage and shoulder impingement.' },
      { name: 'Joint Replacement', desc: 'Hip and knee replacement for advanced arthritis, with post-op rehab guidance.' },
      { name: 'Trauma & Fracture Care', desc: 'Casting, splinting and surgical fixation for accident and fall injuries.' },
    ],
    note: 'Fractures, joint pain, sports injuries & spine care',
    signpost: { label: 'Bone & Joint', doctor: 'Dr. Kolhe' },
  },
  {
    id: 'neuro',
    num: '04',
    color: 'neuro',
    slug: 'neurology',
    dept: 'Infinity Clinic — Neurology',
    name: 'Dr. Pranit Khandait',
    shortName: 'Dr. Khandait',
    cred: 'MBBS · MD (Medicine) · DM (Neurology)',
    role: 'Brain, Spine & Nerve Specialist',
    experience: 'DM Neurology — brain & nerve specialist',
    timing: 'Mon–Sat · Evening OPD · 7:00 PM – 9:00 PM',
    fee: 'From ₹700',
    bio: 'Dr. Khandait is the neurology specialist at Infinity Clinics, seeing patients in the evening OPD from 7 to 9 PM. He manages stroke recovery, epilepsy, migraines, neuropathy and memory concerns — conditions that often need a dedicated neurologist rather than a general physician.',
    whenToVisit: ['Stroke or paralysis', 'Epilepsy / seizures', 'Severe or recurring headaches', 'Numbness or tingling in limbs', 'Memory loss or confusion', 'Neck pain with arm radiation'],
    services: ['Paralysis', 'Epilepsy / Fits', 'Migraine & Headache', 'Vertigo', 'Memory issues', 'Neuropathy', 'Spondylosis'],
    serviceDetails: [
      { name: 'Epilepsy Management', desc: 'Diagnosis, medication tuning and long-term seizure control plans.' },
      { name: 'Stroke & Paralysis Rehab', desc: 'Acute and follow-up care for stroke patients and weakness recovery.' },
      { name: 'Headache & Migraine Clinic', desc: 'Structured treatment for chronic headaches that do not respond to basic painkillers.' },
    ],
    note: 'Evening OPD · 7:00 – 9:00 PM',
    signpost: { label: 'Neurology', doctor: 'Dr. Khandait' },
  },
  {
    id: 'gynae',
    num: '05',
    color: 'gynae',
    slug: 'gynaecology',
    dept: 'Infinity Clinic — Gynaecology',
    name: 'Dr. Shweta Lodhi',
    shortName: 'Dr. Lodhi',
    cred: 'MBBS · DGO · DRM (Diploma in Reproductive Medicine, Germany)',
    role: 'Consultant Obstetrician & Gynaecologist',
    experience: 'DRM from Germany — fertility & high-risk pregnancy',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹600',
    bio: 'Dr. Lodhi brings international reproductive medicine training to Omkar Nagar. She manages routine gynaecology, high-risk pregnancies, infertility work-ups and hormonal disorders — offering women a specialist who can stay with them from pre-conception through delivery and beyond.',
    whenToVisit: ['Irregular or painful periods', 'Pregnancy check-ups', 'High-risk pregnancy monitoring', 'Infertility evaluation', 'PCOS or hormonal imbalance', 'Menopause symptoms'],
    services: ['High-Risk Pregnancy', 'Infertility', 'Hormonal Issues', 'Period Problems'],
    serviceDetails: [
      { name: 'Antenatal & High-Risk Pregnancy', desc: 'Regular scans, monitoring and specialist oversight for complicated pregnancies.' },
      { name: 'Infertility Work-up', desc: 'Hormonal testing, ovulation tracking and treatment planning for couples trying to conceive.' },
      { name: 'PCOS & Hormonal Care', desc: 'Long-term management of polycystic ovaries, thyroid-related cycles and menopause.' },
    ],
    note: "Prenatal, fertility & women's health",
    signpost: { label: 'Gynaecology', doctor: 'Dr. Lodhi' },
  },
];

export const WHY_CARDS = [
  {
    num: '01 — Continuity',
    title: 'Shared address, shared context',
    body: 'See the cardiologist for a check-up and the orthopaedic surgeon for a knee, same building, same week — no separate hospital transfers.',
  },
  {
    num: '02 — Credentials',
    title: 'Named specialists, not general duty doctors',
    body: "Each board carries one doctor's name and post-graduate qualification — DM Cardiology, DM Neurology, fellowship-trained orthopaedics — not a rotating panel.",
  },
  {
    num: '03 — On-site diagnostics',
    title: 'ECG, 2D-ECHO, TMT & endoscopy in-house',
    body: 'Common cardiac and ENT diagnostics happen on the same visit, so you leave with answers, not just another appointment.',
  },
  {
    num: '04 — One front desk',
    title: 'A single number for all five departments',
    body: 'Call 8888 797 624 and the reception routes you to the right specialist — or book online and pick your doctor directly.',
  },
];

export const ABOUT = {
  headline: 'A neighbourhood clinic built like a small hospital.',
  lede: 'Infinity Clinics started with a simple idea for Omkar Nagar families: keep the specialists local, keep the credentials visible, and stop sending patients across Nagpur for every second opinion.',
  story: [
    'On Manewada Ring Road, beside South Point School, five separate specialist practices share one address and one front desk. Each department is led by a named doctor with post-graduate training in their field — not a general physician rotating through different OPD counters.',
    'That structure matters when families deal with more than one health issue at a time. A parent with hypertension, a child with ear pain, and a grandmother with knee arthritis can all be seen under one roof, often in the same week, without losing medical records between buildings.',
    'We invested in on-site diagnostics where it counts most — ECG, 2D-ECHO, TMT for cardiac patients; endoscopy and hearing evaluation for ENT — so the common tests happen on the day of your visit, not three weeks later at another lab.',
  ],
  values: [
    { title: 'Transparency', body: 'Every department board shows the doctor\'s full name and qualifications. You know exactly who you are seeing before you walk in.' },
    { title: 'Accessibility', body: 'Street parking for two-wheelers at the gate. One phone number. Evening neurology OPD for working families.' },
    { title: 'Continuity', body: 'Follow-ups stay with the same specialist. Your cardiologist sees your ECG history; your gynaecologist tracks your pregnancy — not a different face each visit.' },
  ],
};

export const VISIT_STEPS = [
  { step: '01', title: 'Call or book online', body: 'Reach us at 8888 797 624 or use the online booking form. Tell us which department you need — we will confirm the specialist\'s slot.' },
  { step: '02', title: 'Arrive with basics', body: 'Bring previous reports, current medicines and a valid ID. First-time patients: arrive 10 minutes early for registration.' },
  { step: '03', title: 'See your specialist', body: 'You will be seen by the named doctor for that department — not referred to a junior or a rotating panel.' },
  { step: '04', title: 'Diagnostics on-site', body: 'If ECG, echo, endoscopy or other on-site tests are needed, most can be done the same day without a separate lab visit.' },
];

export const FAQ = [
  { q: 'Do I need an appointment?', a: 'Appointments are recommended so you get a confirmed slot with the right specialist. Walk-ins are accepted subject to availability — call ahead on busy days.' },
  { q: 'Which doctor should I see?', a: 'Call our front desk at 8888 797 624 and describe your symptoms. We will guide you to cardiology, ENT, orthopaedics, neurology or gynaecology. When in doubt, a phone call saves a wasted trip.' },
  { q: 'What are the neurology OPD timings?', a: 'Dr. Pranit Khandait sees patients in the evening OPD from 7:00 PM to 9:00 PM, Monday to Saturday. Other departments run morning and evening slots — call to confirm for the day you plan to visit.' },
  { q: 'Is parking available?', a: 'Street parking for two-wheelers is available at the gate. Four-wheeler parking is limited on Manewada Ring Road — we recommend auto or two-wheeler where possible.' },
  { q: 'Do you accept health insurance?', a: 'Please check with the front desk at the time of your visit regarding cashless or reimbursement policies for your specific insurer and procedure.' },
  { q: 'Can I book for a family member?', a: 'Yes. When booking online, enter the patient\'s name and phone number. For children or elderly relatives, you may use your own phone number for confirmation.' },
];

export const FALLBACK_TESTIMONIALS = [
  { patient_name: 'Ramesh K.', department: 'Cardiology', content: 'Dr. Maske explained my ECG results clearly and arranged angiography the same week. Very professional — I did not have to go to another hospital for the procedure.', rating: 5 },
  { patient_name: 'Sunita M.', department: 'Gynaecology', content: 'Visited Dr. Lodhi for a high-risk pregnancy follow-up. The clinic is well organised and the staff helped with all my reports in one place.', rating: 5 },
  { patient_name: 'Amit P.', department: 'Orthopaedics', content: 'Dr. Kolhe treated my knee injury with arthroscopy. Recovery was faster than I expected. Good to have a fellowship-trained surgeon in Omkar Nagar itself.', rating: 5 },
  { patient_name: 'Priya S.', department: 'ENT', content: 'My son had recurring ear infections. Dr. Moon found the root cause and we have not been back in six months. Endoscopy was done on-site — very convenient.', rating: 5 },
  { patient_name: 'Vikram D.', department: 'Neurology', content: 'Evening OPD timing suited my office hours. Dr. Khandait took time to explain my migraine triggers and adjusted medication properly.', rating: 5 },
  { patient_name: 'Anjali R.', department: 'General', content: 'My parents see the cardiologist and I see the orthopaedic surgeon — same building, same week. That is why we chose Infinity Clinics over running around Nagpur.', rating: 5 },
];

export const ON_SITE_DIAGNOSTICS = [
  { name: 'ECG', dept: 'Cardiology', desc: 'Instant heart rhythm recording during your cardiac visit.' },
  { name: '2D-ECHO', dept: 'Cardiology', desc: 'Ultrasound imaging of heart structure and function.' },
  { name: 'TMT', dept: 'Cardiology', desc: 'Treadmill stress test for exercise-related symptoms.' },
  { name: 'Endoscopy', dept: 'ENT', desc: 'Nasal and sinus endoscopy for chronic ENT conditions.' },
  { name: 'Hearing Evaluation', dept: 'ENT', desc: 'Assessment and hearing-aid fitting on referral.' },
];
