export const CLINIC = {
  name: 'Pulse Multi-Specialty Clinic',
  tagline: 'Metro Health Park · City Centre',
  phone: '9876543210',
  phoneDisplay: '9876 543 210',
  email: 'contact@pulseclinic.demo',
  address: 'Plot No. 42, Metro Health Park, Central Avenue, City Centre – 400001',
  ribbon: 'Plot No. 42, Metro Health Park, Central Avenue, City Centre – 400001',
  mapQuery: 'Pulse+Multi+Specialty+Clinic+Central+Avenue',
  whatsapp: '919876543210',
  landmark: 'Opposite Metro Central Station, Beside City Medical Arcade',
  established: 'Multi-specialty practice · City Centre',
};

export const DEPARTMENTS = [
  {
    id: 'heart',
    num: '01',
    color: 'heart',
    slug: 'cardiology',
    dept: 'Pulse Heart & Vascular Clinic',
    name: 'Dr. Aarav Sharma',
    shortName: 'Dr. Sharma',
    cred: 'MBBS · MD Internal Medicine · DM Cardiology',
    role: 'Consultant Interventional Cardiologist',
    experience: '15+ years in clinical and interventional cardiology',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹800',
    bio: 'Dr. Sharma leads the heart clinic with DM Cardiology training. He manages everything from routine hypertension follow-ups to interventional procedures — angiography and angioplasty — so patients receive comprehensive cardiac evaluations in one centre.',
    whenToVisit: ['Chest pain or tightness', 'High blood pressure or diabetes with heart risk', 'Palpitations or irregular heartbeat', 'Breathlessness on exertion', 'Post-heart-attack follow-up', 'Pre-surgery cardiac clearance'],
    services: ['Angiography', 'Angioplasty', 'ECG', '2D-ECHO', 'TMT'],
    serviceDetails: [
      { name: 'ECG & 2D-ECHO', desc: 'Same-visit cardiac imaging — no separate lab appointment for basic heart assessment.' },
      { name: 'TMT (Stress Test)', desc: 'Treadmill testing for exercise-induced symptoms and fitness clearance.' },
      { name: 'Angiography & Angioplasty', desc: 'Interventional procedures for blocked arteries, performed by a DM Cardiologist.' },
    ],
    note: 'For chest pain, hypertension, diabetes & heart-rhythm concerns',
    signpost: { label: 'Heart Clinic', doctor: 'Dr. Sharma' },
  },
  {
    id: 'ent',
    num: '02',
    color: 'ent',
    slug: 'ent',
    dept: 'ENT & Hearing Clinic',
    name: 'Dr. Priya Nair',
    shortName: 'Dr. Nair',
    cred: 'MBBS · MS (ENT) · DNB-ENT',
    role: 'Certified in Vertigo & Endoscopic Sinus Surgery',
    experience: 'ENT surgeon with advanced sinus & balance training',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹600',
    bio: 'Dr. Nair handles the full spectrum of ear, nose, and throat conditions — from childhood ear infections to adult sinus disease and vertigo. Endoscopic sinus evaluations and hearing-aid assessments are available on-site.',
    whenToVisit: ['Chronic sinusitis or nasal blockage', 'Recurrent ear infections', 'Hearing loss or ringing (tinnitus)', 'Dizziness or vertigo', 'Throat pain or voice changes', 'Thyroid swelling in the neck'],
    services: ['Allergy', 'Endoscopy', 'Vertigo / Dizziness', 'Thyroid', 'Hearing aid fitting'],
    serviceDetails: [
      { name: 'Endoscopic Sinus Surgery', desc: 'Minimally invasive treatment for chronic sinus and nasal polyps.' },
      { name: 'Vertigo & Balance Clinic', desc: 'Specialised assessment for dizziness, BPPV and inner-ear disorders.' },
      { name: 'Hearing Aid Fitting', desc: 'Evaluation and fitting for age-related or noise-induced hearing loss.' },
    ],
    note: 'Ear, nose, throat & balance disorders',
    signpost: { label: 'ENT Clinic', doctor: 'Dr. Nair' },
  },
  {
    id: 'ortho',
    num: '03',
    color: 'ortho',
    slug: 'orthopaedics',
    dept: 'Bone & Joint Care Clinic',
    name: 'Dr. Rohan Kapoor',
    shortName: 'Dr. Kapoor',
    cred: 'MBBS · MS Orthopaedics · Fellow in Joint Replacement & Arthroscopy',
    role: 'Consultant Orthopaedic & Joint Replacement Surgeon',
    experience: 'Fellowship-trained orthopaedic surgeon',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹700',
    bio: 'Dr. Kapoor specialises in joint preservation, sports injuries, and spine care. He offers advanced surgical and non-surgical options for knee, shoulder, and hip problems — from fracture fixation to keyhole arthroscopy.',
    whenToVisit: ['Knee or shoulder pain', 'Sports injuries', 'Fractures and trauma', 'Joint stiffness or arthritis', 'Back pain and spondylosis', 'Difficulty walking or climbing stairs'],
    services: ['Arthroscopy', 'Joint Replacement', 'Spine', 'Trauma', 'Pain Management'],
    serviceDetails: [
      { name: 'Arthroscopy', desc: 'Keyhole surgery for ACL tears, meniscus damage and shoulder impingement.' },
      { name: 'Joint Replacement', desc: 'Hip and knee replacement for advanced arthritis, with post-op rehab guidance.' },
      { name: 'Trauma & Fracture Care', desc: 'Casting, splinting and surgical fixation for accident and fall injuries.' },
    ],
    note: 'Fractures, joint pain, sports injuries & spine care',
    signpost: { label: 'Bone & Joint', doctor: 'Dr. Kapoor' },
  },
  {
    id: 'neuro',
    num: '04',
    color: 'neuro',
    slug: 'neurology',
    dept: 'Neurology & Stroke Clinic',
    name: 'Dr. Ananya Sen',
    shortName: 'Dr. Sen',
    cred: 'MBBS · MD (Medicine) · DM (Neurology)',
    role: 'Brain, Spine & Nerve Specialist',
    experience: 'DM Neurology — brain & nerve specialist',
    timing: 'Mon–Sat · Evening OPD · 7:00 PM – 9:00 PM',
    fee: 'From ₹700',
    bio: 'Dr. Sen is the neurology specialist at Pulse Clinic, seeing patients in the evening OPD from 7 to 9 PM. She manages stroke recovery, epilepsy, migraines, neuropathy, and memory concerns.',
    whenToVisit: ['Stroke or paralysis', 'Epilepsy / seizures', 'Severe or recurring headaches', 'Numbness or tingling in limbs', 'Memory loss or confusion', 'Neck pain with arm radiation'],
    services: ['Paralysis', 'Epilepsy / Fits', 'Migraine & Headache', 'Vertigo', 'Memory issues', 'Neuropathy', 'Spondylosis'],
    serviceDetails: [
      { name: 'Epilepsy Management', desc: 'Diagnosis, medication tuning and long-term seizure control plans.' },
      { name: 'Stroke & Paralysis Rehab', desc: 'Acute and follow-up care for stroke patients and weakness recovery.' },
      { name: 'Headache & Migraine Clinic', desc: 'Structured treatment for chronic headaches that do not respond to basic painkillers.' },
    ],
    note: 'Evening OPD · 7:00 – 9:00 PM',
    signpost: { label: 'Neurology', doctor: 'Dr. Sen' },
  },
  {
    id: 'gynae',
    num: '05',
    color: 'gynae',
    slug: 'gynaecology',
    dept: 'Women’s Health & Maternity',
    name: 'Dr. Kavita Roy',
    shortName: 'Dr. Roy',
    cred: 'MBBS · MD (Obstetrics & Gynaecology) · Fellowship in Reproductive Medicine',
    role: 'Consultant Obstetrician & Gynaecologist',
    experience: 'Reproductive medicine and fertility care specialist',
    timing: 'Mon–Sat · Morning & evening OPD (call to confirm)',
    fee: 'From ₹600',
    bio: 'Dr. Roy manages routine gynaecology, high-risk pregnancies, infertility work-ups, and hormonal disorders — offering comprehensive care from pre-conception through delivery and beyond.',
    whenToVisit: ['Irregular or painful periods', 'Pregnancy check-ups', 'High-risk pregnancy monitoring', 'Infertility evaluation', 'PCOS or hormonal imbalance', 'Menopause symptoms'],
    services: ['High-Risk Pregnancy', 'Infertility', 'Hormonal Issues', 'Period Problems'],
    serviceDetails: [
      { name: 'Antenatal & High-Risk Pregnancy', desc: 'Regular scans, monitoring and specialist oversight for complicated pregnancies.' },
      { name: 'Infertility Work-up', desc: 'Hormonal testing, ovulation tracking and treatment planning for couples trying to conceive.' },
      { name: 'PCOS & Hormonal Care', desc: 'Long-term management of polycystic ovaries, thyroid-related cycles and menopause.' },
    ],
    note: "Prenatal, fertility & women's health",
    signpost: { label: 'Gynaecology', doctor: 'Dr. Roy' },
  },
];

export const WHY_CARDS = [
  {
    num: '01 — Continuity',
    title: 'Shared address, shared context',
    body: 'See the cardiologist for a check-up and the orthopaedic surgeon for joint pain, in the same facility with connected medical records.',
  },
  {
    num: '02 — Credentials',
    title: 'Named specialists, not general duty doctors',
    body: "Each department carries dedicated specialists and post-graduate qualifications — DM Cardiology, DM Neurology, fellowship-trained orthopaedics.",
  },
  {
    num: '03 — On-site diagnostics',
    title: 'ECG, 2D-ECHO, TMT & endoscopy in-house',
    body: 'Common cardiac and ENT diagnostics happen on the same visit, so you leave with answers promptly.',
  },
  {
    num: '04 — One front desk',
    title: 'A single number for all five departments',
    body: 'Call 9876 543 210 and the reception routes you to the right specialist — or book online and pick your doctor directly.',
  },
];

export const ABOUT = {
  headline: 'A multi-specialty medical centre built around patient care.',
  lede: 'Pulse Multi-Specialty Clinic brings together experienced consultants, modern diagnostics, and synchronized care under one roof for families across the city.',
  story: [
    'At Metro Health Park on Central Avenue, five distinct specialist practices share one modern facility and one unified front desk. Each department is led by a named specialist with post-graduate credentials in their field.',
    'That integrated structure matters when families deal with multiple health needs at the same time. Cardiac follow-ups, pediatric ENT visits, and orthopaedic consultations can all be handled in the same location without misplaced records or scattered appointments.',
    'We equipped our centre with on-site diagnostics — ECG, 2D-ECHO, TMT for cardiac care; endoscopy and hearing evaluations for ENT — so routine diagnostic tests are completed promptly during your visit.',
  ],
  values: [
    { title: 'Transparency', body: 'Every department board shows the doctor\'s full name and qualifications. You know exactly who you are seeing before you walk in.' },
    { title: 'Accessibility', body: 'Convenient ground-level access, patient parking, online booking, and dedicated evening OPD slots for working professionals.' },
    { title: 'Continuity', body: 'Follow-ups stay with the same specialist across your care journey.' },
  ],
};

export const VISIT_STEPS = [
  { step: '01', title: 'Call or book online', body: 'Reach us at 9876 543 210 or use the online booking form. Choose your department and preferred consultation slot.' },
  { step: '02', title: 'Arrive with basics', body: 'Bring previous reports, current medicines, and a valid photo ID. First-time patients: arrive 10 minutes early for registration.' },
  { step: '03', title: 'See your specialist', body: 'You will be seen directly by the named consultant doctor for that department.' },
  { step: '04', title: 'Diagnostics on-site', body: 'If ECG, echo, endoscopy, or other on-site tests are needed, they can be done during your visit.' },
];

export const FAQ = [
  { q: 'Do I need an appointment?', a: 'Appointments are recommended so you get a confirmed slot with minimal waiting time. Walk-ins are accepted subject to daily slot availability.' },
  { q: 'Which doctor should I see?', a: 'Call our front desk at 9876 543 210 and describe your symptoms. We will guide you to cardiology, ENT, orthopaedics, neurology, or gynaecology.' },
  { q: 'What are the neurology OPD timings?', a: 'Dr. Ananya Sen sees patients in the evening OPD from 7:00 PM to 9:00 PM, Monday to Saturday. Other departments run morning and afternoon slots.' },
  { q: 'Is parking available?', a: 'Dedicated patient parking for both two-wheelers and four-wheelers is available at Metro Health Park.' },
  { q: 'Do you accept health insurance?', a: 'Please check with the front desk at the time of your visit regarding cashless and reimbursement documentation for your insurer.' },
  { q: 'Can I book for a family member?', a: 'Yes. When booking online, enter the patient\'s name and medical details. You may use your own contact number for confirmation updates.' },
];

export const FALLBACK_TESTIMONIALS = [
  { patient_name: 'Ramesh K.', department: 'Cardiology', content: 'Dr. Sharma explained my ECG results clearly and arranged all cardiac tests the same week. Very professional and helpful experience.', rating: 5 },
  { patient_name: 'Sunita M.', department: 'Gynaecology', content: 'Visited Dr. Roy for a pregnancy follow-up. The clinic is well organised and the staff handled all my reports seamlessly.', rating: 5 },
  { patient_name: 'Amit P.', department: 'Orthopaedics', content: 'Dr. Kapoor treated my knee ligament injury and guided my recovery. Excellent orthopaedic surgeon and modern facility.', rating: 5 },
  { patient_name: 'Priya S.', department: 'ENT', content: 'My son had recurring ear infections. Dr. Nair found the root cause with gentle on-site endoscopy.', rating: 5 },
  { patient_name: 'Vikram D.', department: 'Neurology', content: 'Evening OPD timing suited my office schedule. Dr. Sen took time to explain my migraine triggers and adjusted medication properly.', rating: 5 },
  { patient_name: 'Anjali R.', department: 'General', content: 'My parents see the cardiologist and I see the orthopaedic surgeon — in the same medical centre. Extremely convenient and well run.', rating: 5 },
];

export const ON_SITE_DIAGNOSTICS = [
  { name: 'ECG', dept: 'Cardiology', desc: 'Instant heart rhythm recording during your cardiac visit.' },
  { name: '2D-ECHO', dept: 'Cardiology', desc: 'Ultrasound imaging of heart structure and function.' },
  { name: 'TMT', dept: 'Cardiology', desc: 'Treadmill stress test for exercise-related symptoms.' },
  { name: 'Endoscopy', dept: 'ENT', desc: 'Nasal and sinus endoscopy for chronic ENT conditions.' },
  { name: 'Hearing Evaluation', dept: 'ENT', desc: 'Assessment and hearing-aid fitting on referral.' },
];
